# Generated by Django 2.0.5 on 2018-05-26 12:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('pub_date', models.DateField()),
                ('acceptance_id', models.IntegerField(null=True)),
                ('rejection_id', models.IntegerField(null=True)),
                ('media', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(max_length=1024)),
                ('budget', models.FloatField()),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RejectedAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('advertisement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Advertisement')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Advertiser')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=45, null=True)),
                ('phone', models.CharField(max_length=25, null=True)),
                ('language', models.CharField(default='English', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Country')),
            ],
        ),
        migrations.CreateModel(
            name='TargetedAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='ThemePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ThemePhotosLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ThemeRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ThemesComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=999, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Themes')),
            ],
        ),
        migrations.CreateModel(
            name='TypedWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=1000, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 5, 26, 16, 29, 15, 286407))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, unique=True)),
                ('gender', models.CharField(max_length=1)),
                ('register_date', models.CharField(blank=True, max_length=20, null=True)),
                ('current_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('register_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(max_length=45)),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Setting')),
            ],
        ),
        migrations.AddField(
            model_name='typedwords',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User'),
        ),
        migrations.AddField(
            model_name='themescomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', to_field='username'),
        ),
        migrations.AddField(
            model_name='themerating',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Themes'),
        ),
        migrations.AddField(
            model_name='themephotoslink',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Themes'),
        ),
        migrations.AddField(
            model_name='themephotoslink',
            name='themephoto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.ThemePhoto'),
        ),
        migrations.AddField(
            model_name='themephoto',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Themes'),
        ),
        migrations.AddField(
            model_name='target',
            name='targeted_age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.TargetedAge'),
        ),
        migrations.AddField(
            model_name='setting',
            name='themes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Themes'),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Country'),
        ),
        migrations.AddField(
            model_name='advertisementtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Tag'),
        ),
        migrations.AddField(
            model_name='advertisementcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Category'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='advertiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Advertiser'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Target'),
        ),
        migrations.AddField(
            model_name='acceptedadvertisement',
            name='advertisement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Advertisement'),
        ),
        migrations.AddField(
            model_name='acceptedadvertisement',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Advertiser'),
        ),
    ]
