# Generated by Django 2.0.5 on 2018-05-28 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='typedwords',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 14, 21, 49, 601611)),
        ),
    ]
