# Generated by Django 2.0.5 on 2018-05-28 21:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180528_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_displayed', models.BooleanField(default=False)),
                ('publish_date', models.DateField(default=datetime.date(2018, 5, 29))),
                ('advertisement_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User')),
            ],
        ),
        migrations.AlterField(
            model_name='typedwords',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 1, 28, 18, 945097)),
        ),
    ]
