# Generated by Django 2.0.5 on 2018-05-28 21:36

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180529_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedwords',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 1, 36, 21, 868910)),
        ),
        migrations.AlterField(
            model_name='useradvertisement',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
