# Generated by Django 2.0.5 on 2018-05-29 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180529_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedwords',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 13, 33, 41, 318080)),
        ),
        migrations.AlterField(
            model_name='user',
            name='adv_to_show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.UserAdvertisement'),
        ),
    ]
