# Generated by Django 2.0.5 on 2018-05-29 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180529_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedwords',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 16, 6, 9, 480004)),
        ),
    ]
